/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import dao.Escuela_DAO;
import dominio.Aula;
import javax.swing.JOptionPane;

/**
 *
 * @author Iepiadm
 */
public class Crear_Aula extends javax.swing.JDialog {

    private Aula aula;

    /**
     * Creates new form Crear_Aula
     */
    public Crear_Aula(java.awt.Frame parent, boolean modal, Aula aula) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        if (aula != null) {
            this.aula = aula;
            cargarAula();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mesasText = new javax.swing.JTextField();
        escritoriosText = new javax.swing.JTextField();
        agregarButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sillasText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pizarronesText = new javax.swing.JTextField();
        eliminarButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        agregarButton6.setText("Agregar");
        agregarButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButton6ActionPerformed(evt);
            }
        });

        jLabel1.setText("Agregar Aula");

        jLabel2.setText("agregar número de sillas: ");

        jLabel3.setText("agregar número de mesas:");

        jLabel4.setText("agregar número de escritorios:");

        jLabel5.setText("agregar número de pizarrones:");

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        jButton7.setText("Regresar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(agregarButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sillasText)
                            .addComponent(mesasText)
                            .addComponent(escritoriosText, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(pizarronesText))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sillasText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mesasText, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(escritoriosText, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pizarronesText, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean validarEntradas() {
        if (sillasText.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "falta llenar el campo sillas");
            return false;
        } else if (mesasText.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "falta llenar el campo mesas");
            return false;
        } else if (escritoriosText.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "falta llenar el campo escritorios");
            return false;
        } else if (pizarronesText.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "falta llenar el campo pizarrones");
            return false;
        }
        return true;
    }

    public void cargarAula() {
        sillasText.setText(Integer.toString(aula.getNumeroSillas()));
        mesasText.setText(Integer.toString(aula.getNumeroMesas()));
        escritoriosText.setText(Integer.toString(aula.getNumeroEscritorios()));
        pizarronesText.setText(Integer.toString(aula.getNumeroPizarrones()));
    }
    private void agregarButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButton6ActionPerformed
        if (validarEntradas()) {
            if (aula != null) {
                int s = Integer.parseInt(sillasText.getText());
                int m = Integer.parseInt(mesasText.getText());
                int e = Integer.parseInt(escritoriosText.getText());
                int p = Integer.parseInt(pizarronesText.getText());
                aula.setNumeroSillas(s);
                aula.setNumeroMesas(m);
                aula.setEscritorios(e);
                aula.setNumeroPizarrones(p);

                Escuela_DAO ed = new Escuela_DAO();
                boolean estado = ed.editarAula(aula);
                int guarda = JOptionPane.showConfirmDialog(this, "Desea guardar los cambios?", "Advertencia", JOptionPane.YES_NO_OPTION);
                if (guarda == JOptionPane.YES_OPTION) {
                    if (estado == true) {
                        JOptionPane.showMessageDialog(this, "Se edito correctamente");
                        dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Error al editar");
                }
            } else {

                Aula aul = new Aula();
                int s = Integer.parseInt(sillasText.getText());
                int m = Integer.parseInt(mesasText.getText());
                int e = Integer.parseInt(escritoriosText.getText());
                int p = Integer.parseInt(pizarronesText.getText());
                aul.setNumeroSillas(s);
                aul.setNumeroMesas(m);
                aul.setEscritorios(e);
                aul.setNumeroPizarrones(p);
                
                Escuela_DAO au = new Escuela_DAO();
                if (au.crearAula(aul) == true) {
                    JOptionPane.showMessageDialog(null, "El aula se agregó correctamente");
                    sillasText.setText("");
                    mesasText.setText("");
                    escritoriosText.setText("");
                    pizarronesText.setText("");
                    sillasText.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_agregarButton6ActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        int s = Integer.parseInt(sillasText.getText());
        int m = Integer.parseInt(mesasText.getText());
        int e = Integer.parseInt(escritoriosText.getText());
        int p = Integer.parseInt(pizarronesText.getText());
        aula.setNumeroSillas(s);
        aula.setNumeroMesas(m);
        aula.setEscritorios(e);
        aula.setNumeroPizarrones(p);

        Escuela_DAO ed = new Escuela_DAO();
        boolean estado = ed.eliminarAula(aula);
        int guarda = JOptionPane.showConfirmDialog(this, "Desea guardar los cambios?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (guarda == JOptionPane.YES_OPTION) {
            if (estado == true) {
                JOptionPane.showMessageDialog(this, "Se elimió correctamente");
                dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar");
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Datos_Escuela da = new Datos_Escuela();
        da.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton6;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JTextField escritoriosText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField mesasText;
    private javax.swing.JTextField pizarronesText;
    private javax.swing.JTextField sillasText;
    // End of variables declaration//GEN-END:variables
}
